language: c++
dist: trusty
sudo: required
group: edge
addons:
    apt:
      sources:
      - ubuntu-toolchain-r-test
      packages:
      - gcc-4.9
      - g++-4.9
before_install:
  - travis_retry wget http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1404/x86_64/cuda-repo-ubuntu1404_8.0.44-1_amd64.deb
  - travis_retry sudo dpkg -i cuda-repo-ubuntu1404_8.0.44-1_amd64.deb
  - travis_retry sudo apt-get update -qq
  - travis_retry sudo apt-get install -y cuda-drivers cuda-core-8.0 cuda-cudart-dev-8-0 cuda-cufft-dev-8-0
  - travis_retry sudo apt-get clean
  - export CUDA_HOME=/usr/local/cuda-8.0
  - export LD_LIBRARY_PATH=${CUDA_HOME}/lib64:${LD_LIBRARY_PATH}
  - export PATH=${CUDA_HOME}/bin:${PATH}
  # - sudo rm /usr/bin/g++ /usr/bin/gcc
  # - sudo ln -s /usr/bin/g++-4.9 /usr/bin/g++
  # - sudo ln -s /usr/bin/gcc-4.9 /usr/bin/gcc
script:
  - mkdir build && cd build && cmake .. -DWITH_CUDA=ON -DWITH_BENCHMARK=ON && make
